//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  mindmap: Mindmap;
  mindmapConnection: MindmapConnection;
  resources: Resources;
  resourcesConnection: ResourcesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMindmapArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMindmapConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MindmapFilter>;
};


export type QueryResourcesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResourcesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourcesFilter>;
};

export type DocumentFilter = {
  mindmap?: InputMaybe<MindmapFilter>;
  resources?: InputMaybe<ResourcesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Mindmap | Resources | Folder;

export type MindmapNodesData = {
  __typename?: 'MindmapNodesData';
  label?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  borderColor?: Maybe<Scalars['String']['output']>;
  backgroundColor?: Maybe<Scalars['String']['output']>;
  labelColor?: Maybe<Scalars['String']['output']>;
};

export type MindmapNodesPosition = {
  __typename?: 'MindmapNodesPosition';
  x?: Maybe<Scalars['Float']['output']>;
  y?: Maybe<Scalars['Float']['output']>;
};

export type MindmapNodesStyle = {
  __typename?: 'MindmapNodesStyle';
  width?: Maybe<Scalars['Float']['output']>;
  height?: Maybe<Scalars['Float']['output']>;
  zIndex?: Maybe<Scalars['Float']['output']>;
};

export type MindmapNodes = {
  __typename?: 'MindmapNodes';
  id?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  parentNode?: Maybe<Scalars['String']['output']>;
  draggable?: Maybe<Scalars['Boolean']['output']>;
  data?: Maybe<MindmapNodesData>;
  position?: Maybe<MindmapNodesPosition>;
  style?: Maybe<MindmapNodesStyle>;
};

export type MindmapEdges = {
  __typename?: 'MindmapEdges';
  id?: Maybe<Scalars['String']['output']>;
  source?: Maybe<Scalars['String']['output']>;
  target?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  animated?: Maybe<Scalars['Boolean']['output']>;
  type?: Maybe<Scalars['String']['output']>;
};

export type Mindmap = Node & Document & {
  __typename?: 'Mindmap';
  nodes?: Maybe<Array<Maybe<MindmapNodes>>>;
  edges?: Maybe<Array<Maybe<MindmapEdges>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type MindmapNodesDataFilter = {
  label?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  borderColor?: InputMaybe<StringFilter>;
  backgroundColor?: InputMaybe<StringFilter>;
  labelColor?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type MindmapNodesPositionFilter = {
  x?: InputMaybe<NumberFilter>;
  y?: InputMaybe<NumberFilter>;
};

export type MindmapNodesStyleFilter = {
  width?: InputMaybe<NumberFilter>;
  height?: InputMaybe<NumberFilter>;
  zIndex?: InputMaybe<NumberFilter>;
};

export type MindmapNodesFilter = {
  id?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  parentNode?: InputMaybe<StringFilter>;
  draggable?: InputMaybe<BooleanFilter>;
  data?: InputMaybe<MindmapNodesDataFilter>;
  position?: InputMaybe<MindmapNodesPositionFilter>;
  style?: InputMaybe<MindmapNodesStyleFilter>;
};

export type MindmapEdgesFilter = {
  id?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
  target?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  animated?: InputMaybe<BooleanFilter>;
  type?: InputMaybe<StringFilter>;
};

export type MindmapFilter = {
  nodes?: InputMaybe<MindmapNodesFilter>;
  edges?: InputMaybe<MindmapEdgesFilter>;
};

export type MindmapConnectionEdges = {
  __typename?: 'MindmapConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Mindmap>;
};

export type MindmapConnection = Connection & {
  __typename?: 'MindmapConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MindmapConnectionEdges>>>;
};

export type Resources = Node & Document & {
  __typename?: 'Resources';
  title: Scalars['String']['output'];
  type: Scalars['String']['output'];
  file?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ResourcesFilter = {
  title?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  file?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  description?: InputMaybe<RichTextFilter>;
};

export type ResourcesConnectionEdges = {
  __typename?: 'ResourcesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Resources>;
};

export type ResourcesConnection = Connection & {
  __typename?: 'ResourcesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResourcesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateMindmap: Mindmap;
  createMindmap: Mindmap;
  updateResources: Resources;
  createResources: Resources;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateMindmapArgs = {
  relativePath: Scalars['String']['input'];
  params: MindmapMutation;
};


export type MutationCreateMindmapArgs = {
  relativePath: Scalars['String']['input'];
  params: MindmapMutation;
};


export type MutationUpdateResourcesArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourcesMutation;
};


export type MutationCreateResourcesArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourcesMutation;
};

export type DocumentUpdateMutation = {
  mindmap?: InputMaybe<MindmapMutation>;
  resources?: InputMaybe<ResourcesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  mindmap?: InputMaybe<MindmapMutation>;
  resources?: InputMaybe<ResourcesMutation>;
};

export type MindmapNodesDataMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  borderColor?: InputMaybe<Scalars['String']['input']>;
  backgroundColor?: InputMaybe<Scalars['String']['input']>;
  labelColor?: InputMaybe<Scalars['String']['input']>;
};

export type MindmapNodesPositionMutation = {
  x?: InputMaybe<Scalars['Float']['input']>;
  y?: InputMaybe<Scalars['Float']['input']>;
};

export type MindmapNodesStyleMutation = {
  width?: InputMaybe<Scalars['Float']['input']>;
  height?: InputMaybe<Scalars['Float']['input']>;
  zIndex?: InputMaybe<Scalars['Float']['input']>;
};

export type MindmapNodesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  parentNode?: InputMaybe<Scalars['String']['input']>;
  draggable?: InputMaybe<Scalars['Boolean']['input']>;
  data?: InputMaybe<MindmapNodesDataMutation>;
  position?: InputMaybe<MindmapNodesPositionMutation>;
  style?: InputMaybe<MindmapNodesStyleMutation>;
};

export type MindmapEdgesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
  target?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  animated?: InputMaybe<Scalars['Boolean']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
};

export type MindmapMutation = {
  nodes?: InputMaybe<Array<InputMaybe<MindmapNodesMutation>>>;
  edges?: InputMaybe<Array<InputMaybe<MindmapEdgesMutation>>>;
};

export type ResourcesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  file?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
};

export type MindmapPartsFragment = { __typename: 'Mindmap', nodes?: Array<{ __typename: 'MindmapNodes', id?: string | null, type?: string | null, parentNode?: string | null, draggable?: boolean | null, data?: { __typename: 'MindmapNodesData', label?: string | null, description?: string | null, borderColor?: string | null, backgroundColor?: string | null, labelColor?: string | null } | null, position?: { __typename: 'MindmapNodesPosition', x?: number | null, y?: number | null } | null, style?: { __typename: 'MindmapNodesStyle', width?: number | null, height?: number | null, zIndex?: number | null } | null } | null> | null, edges?: Array<{ __typename: 'MindmapEdges', id?: string | null, source?: string | null, target?: string | null, label?: string | null, animated?: boolean | null, type?: string | null } | null> | null };

export type ResourcesPartsFragment = { __typename: 'Resources', title: string, type: string, file?: string | null, videoUrl?: string | null, thumbnail?: string | null, description?: any | null };

export type MindmapQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MindmapQuery = { __typename?: 'Query', mindmap: { __typename: 'Mindmap', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nodes?: Array<{ __typename: 'MindmapNodes', id?: string | null, type?: string | null, parentNode?: string | null, draggable?: boolean | null, data?: { __typename: 'MindmapNodesData', label?: string | null, description?: string | null, borderColor?: string | null, backgroundColor?: string | null, labelColor?: string | null } | null, position?: { __typename: 'MindmapNodesPosition', x?: number | null, y?: number | null } | null, style?: { __typename: 'MindmapNodesStyle', width?: number | null, height?: number | null, zIndex?: number | null } | null } | null> | null, edges?: Array<{ __typename: 'MindmapEdges', id?: string | null, source?: string | null, target?: string | null, label?: string | null, animated?: boolean | null, type?: string | null } | null> | null } };

export type MindmapConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MindmapFilter>;
}>;


export type MindmapConnectionQuery = { __typename?: 'Query', mindmapConnection: { __typename?: 'MindmapConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MindmapConnectionEdges', cursor: string, node?: { __typename: 'Mindmap', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nodes?: Array<{ __typename: 'MindmapNodes', id?: string | null, type?: string | null, parentNode?: string | null, draggable?: boolean | null, data?: { __typename: 'MindmapNodesData', label?: string | null, description?: string | null, borderColor?: string | null, backgroundColor?: string | null, labelColor?: string | null } | null, position?: { __typename: 'MindmapNodesPosition', x?: number | null, y?: number | null } | null, style?: { __typename: 'MindmapNodesStyle', width?: number | null, height?: number | null, zIndex?: number | null } | null } | null> | null, edges?: Array<{ __typename: 'MindmapEdges', id?: string | null, source?: string | null, target?: string | null, label?: string | null, animated?: boolean | null, type?: string | null } | null> | null } | null } | null> | null } };

export type ResourcesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResourcesQuery = { __typename?: 'Query', resources: { __typename: 'Resources', id: string, title: string, type: string, file?: string | null, videoUrl?: string | null, thumbnail?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResourcesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourcesFilter>;
}>;


export type ResourcesConnectionQuery = { __typename?: 'Query', resourcesConnection: { __typename?: 'ResourcesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResourcesConnectionEdges', cursor: string, node?: { __typename: 'Resources', id: string, title: string, type: string, file?: string | null, videoUrl?: string | null, thumbnail?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const MindmapPartsFragmentDoc = gql`
    fragment MindmapParts on Mindmap {
  __typename
  nodes {
    __typename
    id
    type
    parentNode
    draggable
    data {
      __typename
      label
      description
      borderColor
      backgroundColor
      labelColor
    }
    position {
      __typename
      x
      y
    }
    style {
      __typename
      width
      height
      zIndex
    }
  }
  edges {
    __typename
    id
    source
    target
    label
    animated
    type
  }
}
    `;
export const ResourcesPartsFragmentDoc = gql`
    fragment ResourcesParts on Resources {
  __typename
  title
  type
  file
  videoUrl
  thumbnail
  description
}
    `;
export const MindmapDocument = gql`
    query mindmap($relativePath: String!) {
  mindmap(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MindmapParts
  }
}
    ${MindmapPartsFragmentDoc}`;
export const MindmapConnectionDocument = gql`
    query mindmapConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MindmapFilter) {
  mindmapConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MindmapParts
      }
    }
  }
}
    ${MindmapPartsFragmentDoc}`;
export const ResourcesDocument = gql`
    query resources($relativePath: String!) {
  resources(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResourcesParts
  }
}
    ${ResourcesPartsFragmentDoc}`;
export const ResourcesConnectionDocument = gql`
    query resourcesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResourcesFilter) {
  resourcesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResourcesParts
      }
    }
  }
}
    ${ResourcesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      mindmap(variables: MindmapQueryVariables, options?: C): Promise<{data: MindmapQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MindmapQueryVariables, query: string}> {
        return requester<{data: MindmapQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MindmapQueryVariables, query: string}, MindmapQueryVariables>(MindmapDocument, variables, options);
      },
    mindmapConnection(variables?: MindmapConnectionQueryVariables, options?: C): Promise<{data: MindmapConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MindmapConnectionQueryVariables, query: string}> {
        return requester<{data: MindmapConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MindmapConnectionQueryVariables, query: string}, MindmapConnectionQueryVariables>(MindmapConnectionDocument, variables, options);
      },
    resources(variables: ResourcesQueryVariables, options?: C): Promise<{data: ResourcesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesQueryVariables, query: string}> {
        return requester<{data: ResourcesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesQueryVariables, query: string}, ResourcesQueryVariables>(ResourcesDocument, variables, options);
      },
    resourcesConnection(variables?: ResourcesConnectionQueryVariables, options?: C): Promise<{data: ResourcesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesConnectionQueryVariables, query: string}> {
        return requester<{data: ResourcesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesConnectionQueryVariables, query: string}, ResourcesConnectionQueryVariables>(ResourcesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  